version: '2'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: ["npm", "run", "devdockerstart"]
    working_dir: '/backend'
    environment:
      - PORT=3000
      - MONGO_URL=mongodb
    ports:
      - 3000:3000
    links:
      - mongodb
    volumes:
      - ./backend:/backend

  mongodb:
    image: mongo:3.0.14
    container_name: mongodb
    ports:
      - 27017:27017
