version: '2'
services:
  backend:
    image: mhart/alpine-node:7.5.0
    container_name: backend
    command: ["npm", "run", "devdockerstart"]
    working_dir: '/backend'
    environment:
      - HOSTNAME=localhost
      - PORT=3000
      - MONGO_URL=mongodb
    ports:
      - 3000:3000
    # links:
    #   - mongodb
    volumes:
      - ./backend:/backend
